  [[plugins]]
  repo = 'Shougo/neosnippet.vim'

  [[plugins]]
  repo = 'Shougo/neosnippet-snippets'

  [[plugins]]
  repo = 'fatih/vim-go'

  [[plugins]]
  repo = 'wakatime/vim-wakatime'

  [[plugins]]
  repo = 'jacoborus/tender.vim'

  [[plugins]]
  repo = 'davidhalter/jedi-vim'
