  [[plugins]]
  repo = 'scrooloose/nerdtree'

  [[plugins]]
  repo = 'vim-airline/vim-airline'

  [[plugins]]
  repo = 'https://github.com/freeo/vim-kalisi'

  [[plugins]]
  repo = 'ryanoasis/vim-devicons'

  [[plugins]]
  repo = 'Shougo/denite.nvim'
  if   = '''has('python3')'''

  [[plugins]]
  repo = 'Shougo/unite.vim'

  [[plugins]]
  repo = 'cohama/lexima.vim'

  [[plugins]]
  repo = 'tpope/vim-fugitive'

  [[plugins]]
  repo = 'leafgarland/typescript-vim'

  [[plugins]]
  repo = 'easymotion/vim-easymotion'
  
  [[plugins]]
  repo = 'Shougo/vimproc.vim'
  build = 'make'

  [[plugins]]
  repo = 'Quramy/tsuquyomi'

  [[plugins]]
  repo = 'scrooloose/nerdcommenter'

  [[plugins]]
  repo = 'kassio/neoterm'

  [[plugins]]
  repo = 'Shougo/deoplete.nvim'
  hook_add = 'let g:deoplete#enable_at_startup = 1'

  [[plugins]]
  repo = 'w0rp/ale'

  [[plugins]]
  repo = 'airblade/vim-gitgutter'

  [[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'

  [[plugins]]
  repo = 'Chiel92/vim-autoformat'

  [[plugins]]
  repo = 'Shougo/neosnippet.vim'

  [[plugins]]
  repo = 'Shougo/neosnippet-snippets'

  [[plugins]]
  repo = 'fatih/vim-go'

  [[plugins]]
  repo = 'wakatime/vim-wakatime'

  [[plugins]]
  repo = 'jacoborus/tender.vim'

  [[plugins]]
  repo = 'davidhalter/jedi-vim'

  [[plugins]]
  repo = 'zchee/deoplete-jedi'
