  [[plugins]]
  repo = 'scrooloose/nerdtree'

  [[plugins]]
  repo = 'vim-airline/vim-airline'

  [[plugins]]
  repo = 'https://github.com/freeo/vim-kalisi'

  [[plugins]]
  repo = 'ryanoasis/vim-devicons'
