  [[plugins]]
  repo = 'Shougo/neosnippet.vim'

  [[plugins]]
  repo = 'Shougo/neosnippet-snippets'

  [[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'
  
  [[plugins]]
  repo = 'jacoborus/tender.vim'

  [[plugins]]
  repo = 'kassio/neoterm'
  
  [[plugins]]
  repo = 'tpope/vim-fugitive'

  [[plugins]]
  repo = 'airblade/vim-gitgutter'

  [[plugins]]
  repo = 'easymotion/vim-easymotion'

  [[plugins]]
  repo = 'Shougo/denite.nvim'
  if   = '''has('python3')'''

  [[plugins]]
  repo = 'Shougo/unite.vim'

  [[plugins]]
  repo = 'fatih/vim-go'

  [[plugins]]
  repo = 'davidhalter/jedi-vim'

  [[plugins]]
  repo = 'Shougo/vimproc.vim'
  build = 'make'

  [[plugins]]
  repo = 'Quramy/tsuquyomi'

  [[plugins]]
  repo = 'leafgarland/typescript-vim'

  [[plugins]]
  repo = 'wakatime/vim-wakatime'

  [[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'
