  [[plugins]]
  repo = 'Shougo/neosnippet.vim'

  [[plugins]]
  repo = 'Shougo/neosnippet-snippets'

  [[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'
  
  [[plugins]]
  repo = 'jacoborus/tender.vim'

  [[plugins]]
  repo = 'kassio/neoterm'

  [[plugins]]
  repo = 'airblade/vim-gitgutter'

  [[plugins]]
  repo = 'fatih/vim-go'

  [[plugins]]
  repo = 'davidhalter/jedi-vim'

  [[plugins]]
  repo = 'wakatime/vim-wakatime'

  [[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'
